<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

if(!isset($_GET['b_id']))
{
    die("Error");
}
else
{
    $bill_id=$_GET['b_id'];
}


$root= realpath($_SERVER["DOCUMENT_ROOT"]).'/chanakya';
require_once("$root/include/session_check.php");
//empty the session array whenever this page is opened
if(isset($_SESSION['bill_contents']))
{

  $_SESSION['bill_contents']=array();
}

if($permission=="admin"||$permission=="reception")
{

}
else
{
  die("Unauthorized access");
}


require_once("$root/include/dbconfig.php");

require_once("$root/lib/classes/class.helper.php");



      $dbconfig=new Dbconfig();

   

        try {
            $conn = new PDO("mysql:host=$dbconfig->hostname;dbname=$dbconfig->dbname", $dbconfig->username, $dbconfig->password);
            // set the PDO error mode to exception
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // prepare 
            
          
            $stmt = $conn->prepare("SELECT * FROM bill_contents WHERE bill_id=?");
            $stmt->bindParam(1,$bill_id);
            $stmt->execute();

            $bill_contents= $stmt->fetchAll();

           

            $stmt=null;
            $conn=null;

            }
        
            
            
        catch(PDOException $e)
            {
            echo "DB Connection failed: " . $e->getMessage();
            } 

?>


<!--get the header-->
<?php require_once("$root/include/header.php");?>

 <!--get the sidebar-->
<?php require_once("$root/include/sidebar.php");?>

        <!-- Content Wrapper.-->
        <div class="content-wrapper">

              <!-- Main content -->
              <section class="content" style="width:8in" >

              <!--Make the content to be printed-->
           		<textarea   id="special_bill_pdf" >

                  <p style="text-align:center"><img alt="" src="http://localhost/chanakya/dist/img/logo.png" style="height:122px; width:229px" />&nbsp;&nbsp;</p>

<h1 style="text-align:center"><span style="font-size:26px"><span style="font-family:Arial,Helvetica,sans-serif"><span style="color:#0066cc"><strong>CHANAKYA DIAGNOSTIC LABORATORY</strong></span></span></span></h1>

<p style="text-align:center"><span style="font-size:14px"><span style="color:#0066cc"><span style="font-family:Arial,sans-serif"><strong>BHOJO ROAD, SONARI- 785690, ASSAM, PH. 9954422403/(03772)256576</strong></span></span></span></p>

<hr />
<p><span style="font-size:14px"><span style="font-family:Arial,sans-serif"><strong>ID: 25 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Name of patient: Mr Upen Tanti &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Age: 36 years</strong></span></span></p>

<p><span style="font-size:14px"><span style="font-family:Arial,sans-serif"><strong>Gender: male Contact No: Email ID: </strong></span></span></p>

<p><span style="font-size:14px"><span style="font-family:Arial,sans-serif"><strong>Referenced by: Dr P K Shyam Date: 26-02-2017</strong></span></span></p>

<hr />
<p><br />
&nbsp;</p>

<p><br />
&nbsp;</p>

<p>fdgdgfgdgdgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdg</p>

<p><br />
&nbsp;</p>

<p><br />
&nbsp;</p>

<p><span style="font-family:Arial,sans-serif"><strong>Total:200 </strong></span></p>

<p><br />
&nbsp;</p>

<p><span style="font-family:Arial,sans-serif"><strong>Generated By</strong></span></p>

<p>&nbsp;</p>

                  <?php echo $bill_contents[0]['special_bill_content'] ;?>  

           		</textarea>

              </section>
              <!-- / main content -->
              
               <hr>
               <div class="row">
               <div class="col-sm-4 text-center  ">
                <button type="button" class="btn btn-primary btn-lg" id="special_bill_print_button">Print</button>
               </div>

               <div class="col-sm-4 text-center  ">
                <a href="#" class="btn btn-primary btn-lg" role="button">Create  bill</a>
               </div>

               <div class="col-sm-4 text-center  ">
                <a href="#" class="btn btn-primary btn-lg" role="button">Create  special bill</a>
               </div>
               </div>
        </div>
        <!--content-wrapper -->
       


  <!--get the footer-->
 
<?php require_once("$root/include/footer.php");?>

